scalar Date
scalar String

type User {
  id: String
  firstName: String
  lastName: String
  nickname: String!
  address: String
  bio: String
  createdAt: Date
  updatedAt: Date
}

type Query {
  getAllUsers: [User]
  getUser(nickname: String!): User
}

type Mutation {
  createUser(firstName: String!, lastName: String!, nickname: String!, address: String!, bio: String): User
}